name: Update Gallery

on:
  push:
    paths:
      - 'public/gallery/**'
    branches:
      - main

jobs:
  update-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Update gallery data
        run: node scripts/update-gallery.js

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push if changed
        run: |
          git add public/data/gallery.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git pull --rebase origin main
          git commit -m "Update gallery data"
          git push origin main 